/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c0706ff718423616380ab7a83cb4fb7d)
declare namespace Cloudflare {
	interface Env {
		USER_NOTIFICATION: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
